---

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t azure-terraform-container .

      - name: Run the built image.
        run: docker run --name test-container --entrypoint "/bin/sleep" -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro azdo-agent-linux 60

      - name: Verify tools are accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm terraform version
        
#       - name: Verify certbot version
#         run: docker exec --tty test-container env TERM=xterm certbot

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      uses: docker/build-push-action@v2
      with:
        tags: |
          ghcr.io/tonyskidmore/azure-terraform-container:latest
        file: /Dockerfile
        push: true
